services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main

    container_name: open-webui
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8080:8080

    networks:
      - webui-network

    environment:
      UID: 1000
      PID: 1000
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      WEBUI_SECRET_KEY:

    volumes:
      - ./data/webui:/app/backend/data


networks:
  webui-network:
    driver: bridge
